spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

app:
  recaptcha:
    verify-url: https://www.google.com/recaptcha/api/siteverify
    site-key: 6Lexxj0cAAAAANTux6m5ERA_1mb6xRX8iiplKeIE
    secret-key: 6Lexxj0cAAAAAJ7PqcWViRxQ9XY8VePEHt_4o_d4
